### ISSUE TITLE
Where is the definition of config.dense_by_conv?

### ISSUE THREAD

**Issue by whuhxb** [LiyaoTang/contrastBoundary#10]
Hi, 

   where to find the definition of config.dense_by_conv in config file? I have try to revise the code onto another task, but met a bug in dealing with this. Thanks.

Best.

**Comment by LiyaoTang** [comment]
Hi, it is quite tricky, as I modify the config file during the import stage. It was only for debug use and turns out to be not necessary. Specifically, by setting `dense_by_conv`, the code use the 1x1conv instead of the dense_layer to perform a single linear mapping.

**Comment by whuhxb** [comment]
@LiyaoTang 
I still have no idea to deal with this problem now. Could you please provide more details about how to set dense_by_conv now?  In which file? Thanks.

**Comment by LiyaoTang** [comment]
Hi. Could you provide the error message? Or, what is the problem you are trying to solve?

**Comment by whuhxb** [comment]
I try to run the CBL on another dataset, and replace the models file from CBL of models file from CloserLook3D, and I have met this error, the lost definition of dense_by_conv. The error is like this:

models/build_models.py", line 182, in __init__
    if config.dense_by_conv:
AttributeError: 'EasyDict' object has no attribute 'dense_by_conv'

**Comment by whuhxb** [comment]
@LiyaoTang 
How to solve this problem? The definition of dense_by_conv.

**Comment by LiyaoTang** [comment]
Hi, it seems that you use easydict as config, which I do not use. You can simply set the 'dense_by_conv' and any other unwanted (but leads to an error) attribute to be empty string `''`

**Comment by whuhxb** [comment]
@LiyaoTang 
I haven't found config file of dense_by_conv in your tensorflow code, and I have ctrl+F to search in each file. I just find dense_by_conv in models/build_models.py and models/basic_operators.py.

**Comment by LiyaoTang** [comment]
Yes, you are right and I do not have such config, because as I mentioned before, it was only for debug use, which was set manually. Since it becomes an obstacle in your situation, you can simply set it to empty string, or delete the if clause. 

Best.

**Comment by whuhxb** [comment]
@LiyaoTang 
OK. Thanks.

**Comment by whuhxb** [comment]
@LiyaoTang 
config.dense_by_conv bug solved.
But I have met another bug, like this, is it also used for debugging?

models/heads/seg_head.py", line 93, in resnet_scene_segmentation_head
    if config.sep_head or config.arch_up:
AttributeError: 'EasyDict' object has no attribute 'sep_head'

**Comment by whuhxb** [comment]
@LiyaoTang 
I have searched sep_head in config/s3dis.py, like this:
    @property
    def sep_head(self): return any(h.startswith(i) for i in ['multi'] for h in self.arch_out)
But, how to convert the definition of sep_head with config of EasyDict like this(https://github.com/yanx27/SensatUrban_sol_tf/blob/main/utils/config.py):
import yaml
from easydict import EasyDict as edict

config = edict()
# ---------------------------------------------------------------------------- #
# Training
# ---------------------------------------------------------------------------- #
config.max_epoch = 600
config.batch_size = 16
config.base_learning_rate = 0.002
config.optimizer = 'sgd'
config.momentum = 0.9
config.activation_fn = 'leaky_relu'
config.init = 'xavier'
config.weight_decay = 0.0
config.bn_momentum = 0.99
config.bn_eps = 1e-3
config.grad_norm = 100
config.decay_epoch = 10
config.decay_rate = 0.75
config.epoch_steps = 500
config.validation_size = 50
# ---------------------------------------------------------------------------- #
# Model and Data
# ---------------------------------------------------------------------------- #
config.num_classes = 0
config.num_parts = []
config.in_features_dim = 3
config.bottleneck_ratio = 4
config.depth = 1
config.first_features_dim = 72
config.num_layers = 5
config.global_pooling = 'avg'
config.first_subsampling_dl = 0.02
config.density_parameter = 5.0
config.in_radius = 2.0
# data augmentation
config.augment_scale_anisotropic = True
config.augment_symmetries = [False, False, False]
config.augment_rotation = 'none'
config.augment_scale_min = 0.6
config.augment_scale_max = 1.4
config.augment_noise = 0.002
config.augment_color = 0.8

# ---------------------------------------------------------------------------- #
# io and misc
# ---------------------------------------------------------------------------- #
config.num_gpus = 0
config.num_threads = 0
config.gpus = []
config.load_path = ''
config.print_freq = 10
config.save_freq = 10
config.val_freq = 10
config.log_dir = ''

# ---------------------------------------------------------------------------- #
# Local Aggreagtion Operator
# ---------------------------------------------------------------------------- #
config.local_aggreagtion = 'pospool'
# PosPool
config.pospool = edict()
config.pospool.position_embedding = 'xyz'
config.pospool.reduction = 'mean'
config.pospool.output_conv = False
# Adaptive Weight
config.adaptive_weight = edict()
config.adaptive_weight.local_input_feature = 'dp'
config.adaptive_weight.reduction = 'mean'
config.adaptive_weight.shared_channels = 1
config.adaptive_weight.fc_num = 1
config.adaptive_weight.weight_softmax = False
config.adaptive_weight.output_conv = False
# Point-wise MLP
config.pointwisemlp = edict()
config.pointwisemlp.local_input_feature = 'dp_fj'
config.pointwisemlp.fc_num = 1
config.pointwisemlp.reduction = 'max'
# Pseudo Grid
config.pseudo_grid = edict()
config.pseudo_grid.fixed_kernel_points = 'center'
config.pseudo_grid.KP_influence = 'linear'
config.pseudo_grid.KP_extent = 1.0
config.pseudo_grid.num_kernel_points = 15
config.pseudo_grid.convolution_mode = 'sum'
config.pseudo_grid.output_conv = False


def update_config(config_file):
    with open(config_file) as f:
        exp_config = edict(yaml.load(f, Loader=yaml.FullLoader))
        for k, v in exp_config.items():
            if k in config:
                if isinstance(v, dict):
                    for vk, vv in v.items():
                        config[k][vk] = vv
                else:
                    config[k] = v
            else:
                raise ValueError(f"key {k} must exist in config.py")

**Comment by whuhxb** [comment]
@LiyaoTang 
I try to fuse these two codes to run on another dataset. But, you re-define the config file for each dataset.

**Comment by LiyaoTang** [comment]
Yes, but I do have a base class defined in config/base.py. You may want to use that.

**Comment by whuhxb** [comment]
@LiyaoTang 
How to define these two in EasyDict like this link https://github.com/yanx27/SensatUrban_sol_tf/blob/main/utils/config.py:

def arch_out(self):  # head
        out = self._ops.split('|')[1:]
        if not out or not any(h.split('-')[0] in ['mlp', 'multi'] for h in out):
            # add main-head if not present
            out = ['mlp-1-xen'] + out
        return 

def sep_head(self): return any(h.startswith(i) for i in ['multi'] for h in self.arch_out)

**Comment by LiyaoTang** [comment]
I'm sorry that I really cannot help there because it's a new codebase for me and I'm not sure what you want to achieve.

If you really want to use the easydict, you can check the output of log file, where the training scripts print out the config in use. You can then check and set the corresponding attributes into the easydict. However, as you may notice, I provide a default value `''` to any un-set attribute.

**Comment by whuhxb** [comment]
@LiyaoTang 
To make it simple, I want to use CBL tensorflow version on a new dataset: SensatUrban like this link: https://github.com/yanx27/SensatUrban_sol_tf.  This link adopts SensatUrban dataset and works a CloserLook3D. There are two ways to suit CBL on SensatUrban dataset. 
1. If I use SensatUrban_sol_tf on SensatUrban dataset, and also use CBL, then I will change the model file to suit it, then I met the error of sep_head and arch_out. I'm not sure which way is better for me to try on SensatUrban dataset.
2. If I use CBL tensorflow code, then I need to change dataloader section to suit it for SensatUrban dataset.

I'm trying these two ways, but I still met errors. And, I'm not sure which way is better.
Best regards.
Xiaobing

**Comment by LiyaoTang** [comment]
Hi, I think it's better to go for the second way, as adapting the dataset loader sounds simpler for me.

Yet, if you want to go the first way, you may just copy the config generated from my code (printed out at the beginning of model training) and paste it like plain string.

**Comment by whuhxb** [comment]
@LiyaoTang 
OK. I'm trying the second way. If any questions, I will seek for your help.
