### ISSUE TITLE
Some problems when I load s3dis dataset

### ISSUE THREAD

**Issue by yuchenlichuck** [LiyaoTang/contrastBoundary#11]
File "/home/liy0r/cvpr/contrastBoundary/tensorflow/models/../datasets/tf_s3dis_dataset.py", line 166, in <listcomp>
    object_data = np.array([[float(x) for x in line.split()] for line in f])
ValueError: could not convert string to float: '103.0\x100000'

**Comment by LiyaoTang** [comment]
Yes, that's a small error in S3DIS dataset. You may just manually find that line and delete that character.
