### ISSUE TITLE
Where to set the gpu device ID?

### ISSUE THREAD

**Issue by whuhxb** [LiyaoTang/contrastBoundary#14]
@LiyaoTang 
Hi, where to set the gpu device ID? Thanks.

**Comment by LiyaoTang** [comment]
Hi,

passing via command would do. e.g. `--gpu 0,1,2,3` would use the first 4 gpus.

**Comment by LiyaoTang** [comment]
Could you show me the command you use to run the code? As well as the output of nvidia-smi?

**Comment by whuhxb** [comment]
@LiyaoTang 
I have sent the log file via e-mail to you. Thanks.

**Comment by LiyaoTang** [comment]
Hi, it is subtle that you need to specify with `--gpu ,6`

With your command, you can check in the log that the config should be set to use the first 6 gpus (0-5).

**Comment by whuhxb** [comment]
@LiyaoTang 
Hi, if I just want to use GPU card 5 and 6, should I specify with --gpu 5,6, right?

**Comment by LiyaoTang** [comment]
Hi, could you verify that the the provided model, eg s3dis.conv_0, can normally run with the specified device? Do you change anything regarding the config file?

**Comment by whuhxb** [comment]
Hi @LiyaoTang ;

I will have a try. In addition, another question, how to obtain the groundtruth boundary for point clouds? 

Thanks.
