### ISSUE TITLE
How to solve this CUDA problem?

### ISSUE THREAD

**Issue by whuhxb** [LiyaoTang/contrastBoundary#16]
Hi @LiyaoTang;
How to solve this problem?
tensorflow/python/client/session.py", line 1374, in _extend_graph
    tf_session.ExtendSession(self._session)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation gpu_0/model/resnet_backbone/res1_input_conv/L2Loss: {{node gpu_0/model/resnet_backbone/res1_input_conv/L2Loss}}was explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0, /job:localhost/replica:0/task:0/device:XLA_CPU:0, /job:localhost/replica:0/task:0/device:XLA_GPU:0, /job:localhost/replica:0/task:0/device:XLA_GPU:1 ]. Make sure the device specification refers to a valid device.
         [[gpu_0/model/resnet_backbone/res1_input_conv/L2Loss]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 105, in <module>
    trainer.train()
  File "/export/home/hanxiaobing/Documents/PlaneNet_PlaneRCNN/DGCNN_PointNet2/SensatUrban/contrastBoundary/tensorflow_sensaturban/utils/trainer.py", line 91, in train
    sess.run(tf.global_variables_initializer())
  File "/export/home/hanxiaobing/anaconda3/envs/cbl/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/export/home/hanxiaobing/anaconda3/envs/cbl/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/export/home/hanxiaobing/anaconda3/envs/cbl/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/export/home/hanxiaobing/anaconda3/envs/cbl/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation gpu_0/model/resnet_backbone/res1_input_conv/L2Loss: node gpu_0/model/resnet_backbone/res1_input_conv/L2Loss (defined at /export/home/hanxiaobing/Documents/PlaneNet_PlaneRCNN/DGCNN_PointNet2/SensatUrban/contrastBoundary/tensorflow_sensaturban/models/basic_operators.py:128) was explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0, /job:localhost/replica:0/task:0/device:XLA_CPU:0, /job:localhost/replica:0/task:0/device:XLA_GPU:0, /job:localhost/replica:0/task:0/device:XLA_GPU:1 ]. Make sure the device specification refers to a valid device.
         [[gpu_0/model/resnet_backbone/res1_input_conv/L2Loss]]

Errors may have originated from an input operation.
Input Source operations connected to node gpu_0/model/resnet_backbone/res1_input_conv/L2Loss:
 model/resnet_backbone/res1_input_conv/weights/read (defined at /export/home/hanxiaobing/Documents/PlaneNet_PlaneRCNN/DGCNN_PointNet2/SensatUrban/contrastBoundary/tensorflow_sensaturban/models/basic_operators.py:96)

**Comment by LiyaoTang** [comment]
`gpu_0/model/resnet_backbone/res1_input_conv/L2Loss: {{node gpu_0/model/resnet_backbone/res1_input_conv/L2Loss}}was explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0,`

This line means that the code assumes there is one GPU, but there is only CPU available. Please check your `nvidia-smi` output to ensure the GPU is available.

**Comment by whuhxb** [comment]
@LiyaoTang 
OK. Thanks.
How and where to revise the GPU device ID?  The default GPU device IDs are 0 and 1.
