### ISSUE TITLE
How to obtain the groundtruth boundary?

### ISSUE THREAD

**Issue by whuhxb** [LiyaoTang/contrastBoundary#17]
Hi @LiyaoTang ;
How to obtain the groundtruth boundary for point cloud data? As we know, S3DIS dataset is for semantic segmentation, not labeled for boundary.

Or, could you please provide the groundtruth boundary for S3DIS dataset?

Thanks.

**Comment by LiyaoTang** [comment]
Hi,

We calculate the boundary based on the labels.
You could find it at [`get_boundary_mask`](https://github.com/LiyaoTang/contrastBoundary/blob/0490001b1636994b91583eb72c750f7a282d45cf/pytorch/model/basic_operators.py#L69).
