### ISSUE TITLE
How to solve this error in pytorch code?

### ISSUE THREAD

**Issue by whuhxb** [LiyaoTang/contrastBoundary#18]
Hi @LiyaoTang 

How to solve this bug in pytorch code implementation? 

pytorch/util/data_util.py", line 12, in <module>
    from model.basic_operators import get_overlap
ImportError: cannot import name 'get_overlap' from 'model.basic_operators'

Thanks.

**Comment by LiyaoTang** [comment]
That's unnecessary, you can directly delete that import. I've also committed the fix.
