### ISSUE TITLE
Can't train with pytorch

### ISSUE THREAD

**Issue by Chen-yuiyui** [LiyaoTang/contrastBoundary#2]
To train the point-transformer with CBL, run:

bash tool/test.sh s3dis origin_multi-Ua-concat-latent_contrast-Ua-softnn-latent-label-l2-w.1

is that true? I can't start train this code.

**Comment by LiyaoTang** [comment]
Hi, could you verify that you can run with the original point-transformer code first? If the error still persists, please provide more info. e.g. log run with debug flag
