### ISSUE TITLE
What is the value of radius in the sub-scene neighbour?

### ISSUE THREAD

**Issue by Pixie412** [LiyaoTang/contrastBoundary#21]
Hi,

I have a question regarding the the value of radius in the sub-scene boundary. In Eqn. (1), the radius is set to 0.1. I think this is for the input scene. When doing sampling, I guess the radius should be larger？

**Comment by LiyaoTang** [comment]
Yes, you could check the code. I use the corresponding neighbor radius for each down-sampled stage.

**Comment by Pixie412** [comment]
Can you link the relevant code here? Sorry that I didn't find it as I am still trying to understand the code.

**Comment by LiyaoTang** [comment]
Hi, you can check [here](https://github.com/LiyaoTang/contrastBoundary/blob/801bdc790554cb913655a55148cec13889d25278/tensorflow/models/heads/head.py#L561).

**Comment by Pixie412** [comment]
Thanks!
