### ISSUE TITLE
boundary in pytorch implementation

### ISSUE THREAD

**Issue by cb6e310** [LiyaoTang/contrastBoundary#29]
Hi, 
Is boundary computation implemented in PyTorch? I was so far not able to find any.

I appreciate any help you can provide.

**Comment by LiyaoTang** [comment]
Hi,

Thanks for your interest.

Yes, it is. You can find it at [`get_boundary_mask`](https://github.com/LiyaoTang/contrastBoundary/blob/0490001b1636994b91583eb72c750f7a282d45cf/pytorch/model/basic_operators.py#L69).
For the model inference, it is directly implemented in-place [here](https://github.com/LiyaoTang/contrastBoundary/blob/0490001b1636994b91583eb72c750f7a282d45cf/pytorch/model/heads.py#L211C13-L211C13).

Best,
Liyao
