### ISSUE TITLE
What's the model name for CloserLook3D and RandLA-Net?

### ISSUE THREAD

**Issue by whuhxb** [LiyaoTang/contrastBoundary#3]
Hi,

  How to find the model name? For example, CloserLook3D and RandLA-Net. Thanks.

Best.

**Comment by LiyaoTang** [comment]
Hi,

You can find it by printing out the config.

For pretrained model, you could find it in the provided log.

**Comment by whuhxb** [comment]
> Hi,
> 
> You can find it by printing out the config.
> 
> For pretrained model, you could find it in the provided log.

OK. Thanks.
