### ISSUE TITLE
DataSet

### ISSUE THREAD

**Issue by xiyufeng2** [LiyaoTang/contrastBoundary#30]
Hello! During training, I saw that the files of the s3dis dataset were copied to the dev/shm folder, and then the data training was read from this path. This operation is easy to cause memory explosion. Why do you want to do this?
你好！训练时我看s3dis数据集的文件都拷贝到 dev/shm 文件夹中，随后再从该路径读入数据训练。这样的操作很容易导致内存爆炸，请问为何要这样操作呢？感谢回答

**Comment by LiyaoTang** [comment]
Hi,

It's from the original Point-Transformer implementation. /dev/shm stands for shared memory in Linux. I suppose it is for faster data loading such that it avoids reading data from the hard disk in creating each input point cloud.

Best,
Liyao
