### ISSUE TITLE
InvalidArgumentError: Cannot assign a device for operation

### ISSUE THREAD

**Issue by whuhxb** [LiyaoTang/contrastBoundary#4]
Hi, have you ever met this bug?

tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation gpu_0/model/resnet_backbone/res1_input_conv/L2Loss: node gpu_0/model/resnet_backbone/res1_input_conv/L2Loss (defined at /export/home/contrastBoundary/tensorflow/models/basic_operators.py:128) was explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0, /job:localhost/replica:0/task:0/device:XLA_CPU:0, /job:localhost/replica:0/task:0/device:XLA_GPU:0 ]. Make sure the device specification refers to a valid device.
         [[gpu_0/model/resnet_backbone/res1_input_conv/L2Loss]]

Errors may have originated from an input operation.
Input Source operations connected to node gpu_0/model/resnet_backbone/res1_input_conv/L2Loss:
 model/resnet_backbone/res1_input_conv/weights/read (defined at /export/contrastBoundary/tensorflow/models/basic_operators.py:96)
srun: error: node16: task 0: Exited with exit code 1

**Comment by whuhxb** [comment]
@LiyaoTang 
Hi, which file is used to set the GPU device?

**Comment by whuhxb** [comment]
@LiyaoTang 

When using multiple gpus, the error still occurs like this.

tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation gpu_0/model/resnet_backbone/res1_input_conv/L2Loss: node gpu_0/model/resnet_backbone/res1_input_conv/L2Loss (defined at /export/home/hanxiaobing/Documents/PlaneNet_PlaneRCNN/DGCNN_PointNet2/SensatUrban/SensatUrban_code_update/contrastBoundary/tensorflow/models/basic_operators.py:128) was explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0, /job:localhost/replica:0/task:0/device:XLA_CPU:0, /job:localhost/replica:0/task:0/device:XLA_GPU:0, /job:localhost/replica:0/task:0/device:XLA_GPU:1 ]. Make sure the device specification refers to a valid device.
         [[gpu_0/model/resnet_backbone/res1_input_conv/L2Loss]]

Errors may have originated from an input operation.
Input Source operations connected to node gpu_0/model/resnet_backbone/res1_input_conv/L2Loss:
 model/resnet_backbone/res1_input_conv/weights/read (defined at /export/home/hanxiaobing/Documents/PlaneNet_PlaneRCNN/DGCNN_PointNet2/SensatUrban/SensatUrban_code_update/contrastBoundary/tensorflow/models/basic_operators.py:96)

**Comment by whuhxb** [comment]
@LiyaoTang 

I still can solve this problem.

**Comment by LiyaoTang** [comment]
Could you post the logged config and the output of `nvidia-smi` command? There may also be a line in the log indicating the available GPU devises as well.

**Comment by whuhxb** [comment]
@LiyaoTang 

Hi, I can't use GPU now, and I only use CPU. The above error occurs.

**Comment by LiyaoTang** [comment]
Hi,

That's the problem. You may use the flag `--gpu 0` to use CPU only.

**Comment by whuhxb** [comment]
@LiyaoTang 

Where to set the flag  --gpu 0?

**Comment by LiyaoTang** [comment]
This is a command-line option. Please check the `main.py`. You may also just modify the config file `config/s3dis.py`.
