### ISSUE TITLE
get-boundary_mask

### ISSUE THREAD

**Issue by jia1047** [LiyaoTang/contrastBoundary#41]
May I ask what is the use of get-boundary_mask in the PyTorch version of the code? I noticed that you did not call this function in your code. Its function is to distinguish the boundary points of the original point cloud. Where can I use this function? thank you!

**Comment by LiyaoTang** [comment]
Hi, thanks for your interest.

For PyTorch code, it's relatively easy to get the boundary, so I put it in place. This function is probably left over there.
