### ISSUE TITLE
邻居点选择

### ISSUE THREAD

**Issue by jia1047** [LiyaoTang/contrastBoundary#42]
May I ask, based on your paper and open-source code, how to select k neighbor points within a specified radius? If the number of neighbor points within the specified radius does not reach k, what should I do? Or, if I have a problem with my understanding, what should I do

**Comment by LiyaoTang** [comment]
Hi, Jia,

Thanks for your interest. Indeed, I mainly rely on the pre-defined neighborhood search of the network. 

That is, if the network (e.g., ConvNet) uses radius-search, I would consider all boundary points within this radius neighbor. Similarly, for k-nn search, I would consider all boundary points in this neighbor of k points.

Best,
Liyao
