### ISSUE TITLE
How to run contrastive boundary learning with CloserLook3D baseline?

### ISSUE THREAD

**Issue by whuhxb** [LiyaoTang/contrastBoundary#9]
Hi, 

   How to run contrastive boundary learning with CloserLook3D baseline on S3DIS dataset? Thanks. ConvNet is run by: python main.py -c config.s3dis.conv_0

Best.

**Comment by LiyaoTang** [comment]
Hi,

I'm sorry that I do not understand what you mean by the 'ResNet'.

**Comment by whuhxb** [comment]
@LiyaoTang 
Hi, I mean that how to run PosPool referring CloserLook3D. In your instruction, you give the running code on ConvNet like this: python main.py -c config.s3dis.conv_0, but not on CloserLook3D. 
Thanks.

**Comment by LiyaoTang** [comment]
Hi, you could run by specifying the corresponding config, eg. `-c config.s3dis.pospool_0`.

Additionally, if you like, you can also extend to use the `pseudo-grid` method. But that requires a bit of coding as I did not work on that method, yet it should be similar to how I define the `Pospool` class.

**Comment by whuhxb** [comment]
@LiyaoTang 
OK. How to find the model defination like -c config.s3dis.pospool_0 or -c config.s3dis.conv_0? Is there any other choices?

**Comment by LiyaoTang** [comment]
You can look into each config file. You should also check how the `Config` class is defined in config/base.py
